/* This file is auto-generated by scripts/sync-package-api-groups.ts. */
export const generatedPackageApiGroups: Readonly<Record<string, readonly { readonly title: string; readonly sourcePath: string; readonly exports: readonly string[]; }[]>> = 
{
  "core": [
    {
      "title": "Bootstrap and app",
      "sourcePath": "packages/core/src",
      "exports": [
        "CreateApplication",
        "Bootstrap",
        "XTaskHttpApplication",
        "createHttpAdapter"
      ]
    },
    {
      "title": "DI and components",
      "sourcePath": "packages/core/src/di",
      "exports": [
        "Component",
        "Service",
        "Controller",
        "Repository",
        "AutoWired",
        "Qualifier"
      ]
    },
    {
      "title": "HTTP primitives",
      "sourcePath": "packages/core/src/http",
      "exports": [
        "HttpAdapter",
        "HttpRequestLike",
        "HttpResponseLike",
        "HttpViewResult",
        "view",
        "NodeHttpAdapter",
        "FastifyAdapter"
      ]
    }
  ],
  "common": [
    {
      "title": "Routing decorators",
      "sourcePath": "packages/common/src/decorators/core/server",
      "exports": [
        "Controller",
        "Get",
        "Post",
        "Patch",
        "Delete",
        "UseGuards",
        "UseMiddlewares",
        "UsePipes"
      ]
    },
    {
      "title": "Lifecycle decorators",
      "sourcePath": "packages/common/src/decorators/core/server",
      "exports": [
        "OnEvent",
        "ApplicationRunner",
        "CommandLineRunner"
      ]
    },
    {
      "title": "Validation and types",
      "sourcePath": "packages/common/src",
      "exports": [
        "Logger",
        "ValidationPipe",
        "HANDLERS_KEY",
        "ROUTES_KEY",
        "RunnerMeta"
      ]
    }
  ],
  "express-http": [
    {
      "title": "Adapter runtime",
      "sourcePath": "packages/express-http/src",
      "exports": [
        "ExpressAdapter",
        "view",
        "HttpAdapter",
        "HttpRequestHandler"
      ]
    },
    {
      "title": "Request and response types",
      "sourcePath": "packages/express-http/src/types.ts",
      "exports": [
        "HttpRequestLike",
        "HttpResponseLike",
        "HttpServerOptions",
        "HttpViewResult",
        "HttpAdapterType"
      ]
    },
    {
      "title": "Adapter options",
      "sourcePath": "packages/express-http/src/types.ts",
      "exports": [
        "ExpressAdapterOptions",
        "ExpressTemplateEngineOptions",
        "ExpressStaticFilesOptions"
      ]
    }
  ],
  "fastify-http": [
    {
      "title": "Adapter runtime",
      "sourcePath": "packages/fastify-http/src",
      "exports": [
        "FastifyAdapter",
        "view",
        "HttpAdapter",
        "HttpRequestHandler"
      ]
    },
    {
      "title": "Request and response types",
      "sourcePath": "packages/fastify-http/src/types.ts",
      "exports": [
        "HttpRequestLike",
        "HttpResponseLike",
        "HttpServerOptions",
        "HttpViewResult",
        "HttpAdapterType"
      ]
    },
    {
      "title": "Adapter options",
      "sourcePath": "packages/fastify-http/src/types.ts",
      "exports": [
        "FastifyAdapterOptions",
        "FastifyTemplateEngineOptions",
        "FastifyStaticFilesOptions"
      ]
    }
  ],
  "typeorm": [
    {
      "title": "TypeORM bridge",
      "sourcePath": "packages/typeorm/src/configuration.ts",
      "exports": [
        "registerTypeOrmDataSource",
        "TypeOrmDataSource",
        "InjectDataSource",
        "InjectRepository"
      ]
    },
    {
      "title": "Re-exported ORM APIs",
      "sourcePath": "packages/typeorm/src/index.ts",
      "exports": [
        "DataSource",
        "Entity",
        "Column",
        "PrimaryGeneratedColumn",
        "OneToMany",
        "ManyToOne",
        "Repository"
      ]
    },
    {
      "title": "Lifecycle surface",
      "sourcePath": "packages/typeorm/src/lifecycle.ts",
      "exports": [
        "initializeTypeOrmIntegration",
        "shutdownTypeOrmIntegration"
      ]
    }
  ],
  "cqrs": [
    {
      "title": "Configuration and buses",
      "sourcePath": "packages/cqrs/src",
      "exports": [
        "configureCqrs",
        "Cqrs",
        "CommandBus",
        "QueryBus",
        "EventBus"
      ]
    },
    {
      "title": "Handlers, injectors, and idempotency",
      "sourcePath": "packages/cqrs/src",
      "exports": [
        "CommandHandler",
        "QueryHandler",
        "EventHandler",
        "ProcessManager",
        "Saga",
        "ProjectionRebuilder",
        "IdempotentCommand",
        "InjectCommandBus",
        "InjectQueryBus",
        "InjectEventBus",
        "InjectIdempotencyStore",
        "InjectCqrsLifecycleManager",
        "InjectReadDataSource",
        "InjectWriteDataSource",
        "InjectReadRepository",
        "InjectWriteRepository"
      ]
    },
    {
      "title": "Lifecycle, tokens, and types",
      "sourcePath": "packages/cqrs/src",
      "exports": [
        "CqrsLifecycleManager",
        "initializeCqrsIntegration",
        "shutdownCqrsIntegration",
        "resetCqrsIntegration",
        "getCqrsLifecycleManager",
        "getCommandBusToken",
        "getQueryBusToken",
        "getEventBusToken",
        "getIdempotencyStoreToken",
        "getReadDataSourceToken",
        "getWriteDataSourceToken",
        "getReadRepositoryToken",
        "getWriteRepositoryToken",
        "ICommandHandler",
        "IQueryHandler",
        "IEventHandler",
        "IProcessManager",
        "ISaga",
        "IProjectionRebuilder",
        "ProcessManagerContext",
        "ProjectionRebuildContext",
        "IIdempotencyStore",
        "CqrsOptions"
      ]
    }
  ],
  "security": [
    {
      "title": "Route decorators",
      "sourcePath": "packages/security/src/decorators.ts",
      "exports": [
        "Authenticated",
        "Auth",
        "Roles",
        "AllowAnonymous"
      ]
    },
    {
      "title": "Strategy APIs",
      "sourcePath": "packages/security/src/configuration.ts",
      "exports": [
        "registerJwtStrategy",
        "registerJweStrategy",
        "JwtSecurityStrategy",
        "JweSecurityStrategy"
      ]
    },
    {
      "title": "Injected services",
      "sourcePath": "packages/security/src/lifecycle.ts",
      "exports": [
        "InjectAuthenticationService",
        "InjectAuthorizationService",
        "InjectPassport",
        "InjectSecurityLifecycleManager"
      ]
    }
  ],
  "mailer": [
    {
      "title": "Transport registration",
      "sourcePath": "packages/mailer/src/configuration.ts",
      "exports": [
        "registerMailerTransport",
        "createMailtrapTransportOptions",
        "registerMailerTemplate",
        "InjectMailerTransport"
      ]
    },
    {
      "title": "Service and templates",
      "sourcePath": "packages/mailer/src",
      "exports": [
        "MailerService",
        "InjectMailerService",
        "registerEjsTemplateRenderer",
        "registerHandlebarsTemplateRenderer"
      ]
    },
    {
      "title": "Lifecycle surface",
      "sourcePath": "packages/mailer/src/lifecycle.ts",
      "exports": [
        "InjectMailerLifecycleManager",
        "initializeMailerIntegration",
        "shutdownMailerIntegration"
      ]
    }
  ],
  "internationalization": [
    {
      "title": "Configuration and locales",
      "sourcePath": "packages/internationalization/src/configuration.ts",
      "exports": [
        "configureInternationalization",
        "Internationalization",
        "registerInternationalizationLocale",
        "InternationalizationLocale",
        "InternationalizationResolver"
      ]
    },
    {
      "title": "Translation runtime",
      "sourcePath": "packages/internationalization/src",
      "exports": [
        "InternationalizationService",
        "InjectInternationalizationService",
        "runWithInternationalizationContext"
      ]
    },
    {
      "title": "Formatting and lifecycle",
      "sourcePath": "packages/internationalization/src/lifecycle.ts",
      "exports": [
        "registerInternationalizationFormatter",
        "InjectInternationalizationLifecycleManager",
        "initializeInternationalizationIntegration",
        "shutdownInternationalizationIntegration"
      ]
    }
  ],
  "scheduler": [
    {
      "title": "Scheduling decorators",
      "sourcePath": "packages/scheduler/src/decorators.ts",
      "exports": [
        "Cron",
        "Every",
        "Interval",
        "Timeout"
      ]
    },
    {
      "title": "Runtime control",
      "sourcePath": "packages/scheduler/src/scheduler.service.ts",
      "exports": [
        "SchedulerService",
        "InjectSchedulerService"
      ]
    },
    {
      "title": "Lifecycle surface",
      "sourcePath": "packages/scheduler/src/lifecycle.ts",
      "exports": [
        "InjectSchedulerLifecycleManager",
        "initializeSchedulerIntegration",
        "shutdownSchedulerIntegration"
      ]
    }
  ],
  "cache": [
    {
      "title": "Configuration and models",
      "sourcePath": "packages/cache/src/configuration.ts",
      "exports": [
        "configureCache",
        "registerCacheModel",
        "CacheSettings",
        "CacheModel"
      ]
    },
    {
      "title": "Repository and services",
      "sourcePath": "packages/cache/src",
      "exports": [
        "CacheRepository",
        "CacheService",
        "CacheAdminService",
        "InjectCacheService",
        "InjectCacheRepository"
      ]
    },
    {
      "title": "HTTP caching and management",
      "sourcePath": "packages/cache/src",
      "exports": [
        "HttpCacheService",
        "InjectHttpCacheService",
        "CacheResponse",
        "BrowserCache",
        "CacheView",
        "NoStore",
        "NoCache",
        "VaryBy",
        "createCacheManagementController",
        "InjectCacheAdminService"
      ]
    },
    {
      "title": "Lifecycle surface",
      "sourcePath": "packages/cache/src/lifecycle.ts",
      "exports": [
        "InjectCacheLifecycleManager",
        "initializeCacheIntegration",
        "shutdownCacheIntegration",
        "resetCacheIntegration"
      ]
    }
  ],
  "queues": [
    {
      "title": "Configuration and transports",
      "sourcePath": "packages/queues/src",
      "exports": [
        "configureQueues",
        "registerQueueTransport",
        "registerInMemoryQueueTransport",
        "createRabbitMqTransport",
        "createMqttTransport"
      ]
    },
    {
      "title": "Decorators and injectors",
      "sourcePath": "packages/queues/src",
      "exports": [
        "QueueHandler",
        "QueueSubscribe",
        "QueuePattern",
        "PublishToQueue",
        "InjectQueueService",
        "InjectQueueTransport"
      ]
    },
    {
      "title": "Runtime service and lifecycle",
      "sourcePath": "packages/queues/src",
      "exports": [
        "QueueService",
        "initializeQueueIntegration",
        "shutdownQueueIntegration",
        "getQueueServiceToken",
        "getQueueTransportToken"
      ]
    }
  ],
  "value-objects": [
    {
      "title": "Types and contracts",
      "sourcePath": "packages/value-objects/src/types.ts",
      "exports": [
        "JsonValue",
        "ValueObjectLike",
        "ValueObjectStaticFactory",
        "ValueObjectFactory",
        "TransformValueObjectOptions",
        "ValueObjectFactoryProviderOptions"
      ]
    },
    {
      "title": "Conversion helpers",
      "sourcePath": "packages/value-objects/src/converters.ts",
      "exports": [
        "isValueObject",
        "unwrapValue",
        "parseJsonValue",
        "looksLikeJsonString",
        "toPlainValue",
        "toSerializableValue",
        "toJsonString"
      ]
    },
    {
      "title": "Base value objects",
      "sourcePath": "packages/value-objects/src/value-object.ts",
      "exports": [
        "ValueObject",
        "StringValueObject",
        "NumberValueObject",
        "BooleanValueObject",
        "BigIntValueObject",
        "DateValueObject",
        "JsonValueObject"
      ]
    },
    {
      "title": "Factory helpers",
      "sourcePath": "packages/value-objects/src/factories.ts",
      "exports": [
        "createValueObjectFactory",
        "InjectableValueObjectFactory",
        "ValueObjectFactoryFor",
        "fromPlainValue",
        "fromJsonValue",
        "fromAutoValue"
      ]
    },
    {
      "title": "DTO decorators",
      "sourcePath": "packages/value-objects/src/decorators.ts",
      "exports": [
        "TransformValueObject"
      ]
    }
  ]
};
