export const APP_CONFIG = "APP_CONFIG";
export const APP_DATA_SOURCE = "APP_DATA_SOURCE";
export const NEWS_REPOSITORY = "NEWS_REPOSITORY";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const USER_LOGIN_EVENT_REPOSITORY = "USER_LOGIN_EVENT_REPOSITORY";