import {
  Internationalization,
  InternationalizationLocale,
  InternationalizationResolver,
  registerInternationalizationFormatter,
} from "@xtaskjs/internationalization";
import { readSiteLocaleCookie } from "./site-locales";

registerInternationalizationFormatter("uppercase", ({ value }) => {
  return String(value || "").toUpperCase();
});

registerInternationalizationFormatter("relativeTime", ({ value, locale, options }) => {
  return new Intl.RelativeTimeFormat(locale, { numeric: "auto" }).format(
    Number(value),
    String(options.unit || "day") as Intl.RelativeTimeFormatUnit
  );
});

@Internationalization({
  defaultLocale: "en-US",
  fallbackLocale: "en-US",
  defaultCurrency: "USD",
  defaultTimeZone: "UTC",
})
class SiteInternationalizationConfiguration {}

@InternationalizationResolver(({ request }) => {
  return readSiteLocaleCookie(request);
})
class SiteLocaleCookieResolver {}

@InternationalizationLocale({
  locale: "en-US",
  currency: "USD",
  timeZone: "UTC",
  translations: {
    site: {
      docs: {
        hub: {
          eyebrow: "Documentation",
          title: "One place for xtaskjs architecture, packages, decorators, integrations, and samples.",
          subtitle:
            "Start with the overview, then move into dedicated pages for runtime architecture, package reference, decorator reference, and the official sample applications published in the xtask monorepo.",
          openArchitecture: "Open Architecture",
          browseDecorators: "Browse Decorators",
          stats: "{{packages, number}} packages documented + {{decorators, number}} decorators + {{samples, number}} reference samples",
          onThisPage: "On This Page",
          documentationSections: "Documentation sections",
          repo: "Repo:",
          scope: "Scope: runtime packages, adapters, integrations, and official samples.",
          quickStartEyebrow: "Quick Start",
          quickStartTitle: "Boot the smallest useful xtask application",
          install: "Install",
          bootstrap: "Bootstrap",
          sectionsEyebrow: "Sections",
          sectionsTitle: "Move through the documentation by topic",
          documentationBadge: "Documentation",
          openSection: "Open {{label}}",
          highlightsEyebrow: "Highlights",
          highlightsTitle: "What this documentation focuses on",
          footer: "Documentation section integrated into xtaskjs.io and organized around the upstream monorepo structure.",
        },
        architecture: {
          eyebrow: "Architecture",
          title: "How xtaskjs boots, resolves routes, and extends security through one runtime.",
          subtitle:
            "This page focuses on the framework lifecycle: application bootstrap, request execution, and the security extension points layered onto the same controller pipeline.",
          quickStart: "Quick Start",
          openPackages: "Open Packages",
          bootSequence: "Boot sequence",
          bootSequenceText: "Container discovery, adapter selection, lifecycle startup, and integration initialization.",
          requestPath: "Request path",
          requestPathText: "Route lookup, guards, pipes, middlewares, handlers, and final adapter serialization.",
          securityLayering: "Security layering",
          securityLayeringText: "Strategies, auth services, decorators, and route context enrichment stay DI-aware.",
          documentation: "Documentation",
          focus: "Focus: bootstrap lifecycle, execution flow, and security integration.",
          bootstrapFlowEyebrow: "Bootstrap Flow",
          bootstrapFlowTitle: "How xtaskjs wires the runtime",
          executionFlowEyebrow: "Execution Flow",
          executionFlowTitle: "Request pipeline and security lifecycle",
          requestLifecycle: "HTTP request lifecycle",
          securityLifecycle: "Security extension lifecycle",
        },
        packages: {
          eyebrow: "Packages",
          title: "Reference for the xtaskjs runtime packages and integrations.",
          subtitle:
            "This page maps the main packages in the xtask monorepo, what each package provides, how it fits into the runtime, and which official samples demonstrate it in practice, including the new mailer module.",
          browseCatalog: "Browse Catalog",
          openDecorators: "Open Decorators",
          openPackage: "Open package page",
          backToCatalog: "Back to catalog",
          browseSamples: "Browse samples",
          viewSource: "View source",
          stats: "{{count, number}} packages documented",
          coreRuntime: "Core runtime",
          coreRuntimeText: "Bootstrap, DI container, lifecycle orchestration, and HTTP application startup.",
          adapterLayer: "Adapter layer",
          adapterLayerText: "Express and Fastify adapters preserve the same controller and view contracts.",
          integrations: "Integrations",
          integrationsText: "TypeORM, security, and mailer attach lifecycle-aware persistence, authentication, and email delivery features.",
          documentation: "Documentation",
          focus: "Focus: package responsibilities, integration points, and code examples.",
          catalogEyebrow: "Catalog",
          catalogTitle: "Framework packages in the xtask monorepo",
          sampleCoverage: "Sample coverage: {{sample}}",
          whatItProvides: "What it provides",
          howItFits: "How it fits",
          referenceSamples: "Reference samples: {{sample}}",
          packagePath: "Package path",
          installCommand: "Install command",
          atAGlanceEyebrow: "Overview",
          atAGlanceTitle: "What this package owns in the runtime",
          runtimeChartEyebrow: "Usage Chart",
          runtimeChartTitle: "How strongly this package shapes the runtime",
          flowEyebrow: "Package Flow",
          flowTitle: "How this package moves through xtaskjs runtime phases",
          lifecycleEyebrow: "Lifecycle",
          lifecycleTitle: "How it behaves during bootstrap and shutdown",
          apiEyebrow: "API Surface",
          apiTitle: "Representative exports from the upstream package",
          apiSource: "Source: {{path}}",
          usageEyebrow: "Usage",
          usageTitle: "Typical adoption flow",
          exampleEyebrow: "Example",
          exampleTitle: "Reference snippet",
          samplesEyebrow: "Samples",
          samplesTitle: "Official samples to inspect next",
          relatedEyebrow: "Related",
          relatedTitle: "Packages commonly used with this one",
          scoreLabel: "{{score}}/5",
          openRelatedPackage: "Open package",
          openSample: "Open sample",
        },
        decorators: {
          eyebrow: "Decorators",
          title: "Reference for every public xtaskjs decorator across routing, lifecycle, DI, security, persistence, and mail.",
          subtitle:
            "This page lists the framework decorator surface exposed by the upstream packages, grouped by use case and labeled with the package each decorator comes from, plus small usage examples you can adapt directly.",
          browseCatalog: "Browse Decorators",
          openPackages: "Open Packages",
          stats: "{{decorators, number}} decorators across {{groups, number}} groups",
          groupedByType: "Grouped by type",
          groupedByTypeText: "Routing, lifecycle, DI, security, TypeORM, and mailer decorators are separated so similar APIs stay together.",
          packageAware: "Package-aware",
          packageAwareText: "Every entry shows the package and upstream source path where the decorator lives.",
          exampleDriven: "Example-driven",
          exampleDrivenText: "Each decorator includes a short snippet drawn from the same patterns used in xtaskjs samples and this site.",
          documentation: "Documentation",
          coverage: "Coverage:",
          catalogEyebrow: "Catalog",
          catalogTitle: "Decorator groups by use case",
          groupBadge: "Decorator Group",
          countLabel: "decorators",
        },
        samples: {
          eyebrow: "Samples",
          title: "Official example applications for core, adapters, persistence, and security.",
          subtitle:
            "Use the sample applications as the shortest route into the framework. They show the main runtime combinations shipped in the upstream monorepo, including the dedicated mailer sample, and the endpoints each one exposes.",
          browseCatalog: "Browse Samples",
          openArchitecture: "Open Architecture",
          stats: "{{count, number}} reference samples documented",
          startSmall: "Start small",
          startSmallText: "Use 01-new_app to understand the minimal node-http bootstrap and route registration flow.",
          swapAdapters: "Swap adapters",
          swapAdaptersText: "Compare Express and Fastify samples to see how controllers stay stable while the server changes.",
          addIntegrations: "Add integrations",
          addIntegrationsText: "Move into the TypeORM, security, and mailer samples when you need persistence, protected routes, or outbound email workflows.",
          documentation: "Documentation",
          focus: "Focus: runnable examples, endpoint coverage, and progression paths.",
          catalogEyebrow: "Catalog",
          catalogTitle: "Reference applications shipped in the monorepo",
          endpoints: "Endpoints",
          typicalFlow: "Typical flow",
        },
      },
      header: {
        announcement: "xTaskjs 1.0 is live: role-based accounts, documentation, and a customizable interface.",
        why: "Why xTaskjs",
        learn: "Learn",
        documentation: "Documentation",
        news: "News",
        github: "Open xTaskjs on GitHub",
        login: "Log in",
        register: "Register",
        adminPanel: "Admin Panel",
        dashboard: "Dashboard",
        logout: "Log out",
        menuOpen: "Open menu",
        menuClose: "Close menu",
        themeToDark: "Switch to dark mode",
        themeToLight: "Switch to day mode",
        languageLabel: "Language",
      },
      footer: {
        builtWith: "Built with xTaskjs and inspired by modern developer platform homepages.",
        github: "Access the project on GitHub",
        adminAccess: "Admin Access",
      },
      home: {
        metaTitle: "xTaskjs",
        eyebrow: "xTaskjs Framework",
        title: "Build resilient Node.js workflows with confidence.",
        tagline: "Modern workflow orchestration with xTaskjs",
        stack:
          "Powered by decorators, lifecycle hooks, and a class-based application kernel",
        quickStart: "Quick Start",
        exploreGithub: "Explore on GitHub",
        productionReady: "Production-ready stack",
        productionItems: {
          one: "Composable modules with dependency injection patterns",
          two: "Express adapter support with template rendering",
          three: "Shared decorators and common tooling in one ecosystem",
        },
        learnTitle: "Learn xTaskjs",
        guidesTitle: "Guides",
        guidesBody: "Start from zero and ship your first xTaskjs application quickly.",
        guidesAction: "Open quick start",
        referenceTitle: "Reference",
        referenceBody: "Understand adapters, decorators, view rendering, and lifecycle hooks.",
        referenceAction: "Browse packages",
        examplesTitle: "Examples",
        examplesBody: "Use practical code samples for APIs, jobs, queues, and orchestration.",
        examplesAction: "See samples",
        projectsTitle: "xTaskjs Projects",
        publishedOnNpm: "Published on npm: {{date}}",
        npmUnavailable: "npm data unavailable",
        openDocumentationHub: "Open Documentation Hub",
        communityTitle: "Community",
        communityBody: "Follow updates, contribute modules, and discuss roadmap priorities.",
        supportTitle: "Support",
        supportBody: "Need help in production? Open an issue or collaborate with maintainers.",
        latestNewsTitle: "Latest News",
        latestNewsEmptyTitle: "No news yet",
        latestNewsEmptyBody: "Published updates will appear here as soon as the admin posts them.",
        openFullNews: "Open full news section",
      },
      news: {
        metaTitle: "xTaskjs News",
        eyebrow: "xTaskjs Newsroom",
        title: "Framework releases, roadmap milestones, and community updates.",
        subtitle: "Everything happening around xTaskjs in one place.",
        latestNewsTitle: "Latest News",
        published: "Published {{date}}",
        emptyTitle: "No published news yet",
        emptyBody: "The team has not published updates yet. Check back soon.",
      },
    },
    auth: {
      admin: {
        metaTitle: "Admin Login",
        eyebrow: "xTaskjs Admin",
        title: "News Management Login",
        subtitle: "Sign in with an administrator account to manage users and publication updates.",
        accessTitle: "Administrator Access",
        username: "Username",
        password: "Password",
        submit: "Log in",
        standardLogin: "Standard login",
        backToNews: "Back to news",
        expired: "Your login challenge expired. Start again.",
      },
      login: {
        metaTitle: "Log In",
        eyebrow: "Account Access",
        title: "Log in to your xTaskjs account",
        subtitle:
          "Administrators manage platform content and users. Registered users access their personalized dashboard.",
        formTitle: "Log In",
        identifier: "Username or email",
        password: "Password",
        submit: "Log in",
        forgotPassword: "Forgot password?",
        newHere: "New here?",
        newHereBody:
          "Create a user account to access your dashboard and keep your profile ready for future platform features.",
        createAccount: "Create an account",
        newHereNote:
          "Administrators can also use the standard login form. Admin-only operations remain protected by role checks.",
        invalidCredentials: "Invalid credentials. Please try again.",
        verified: "Email verified. Enter your credentials to receive a two-factor code.",
        reset: "Password updated. Enter your credentials to receive a two-factor code.",
        expired:
          "Your login challenge expired. Start again with your username/email and password.",
      },
      register: {
        metaTitle: "Create Account",
        eyebrow: "Registration",
        title: "Create your xTaskjs account",
        subtitle:
          "Registration creates a standard user account, then sends an email verification code before the first authenticated session is allowed.",
        formTitle: "Register",
        fullName: "Full name",
        username: "Username",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm password",
        submit: "Create account",
        alreadyRegistered: "Already registered?",
        alreadyRegisteredBody:
          "Use the login screen to access your dashboard or, if you are an administrator, the admin management area.",
        goToLogin: "Go to login",
        note:
          "Passwords must contain at least 8 characters, and new accounts must verify their email before login.",
        allFieldsRequired: "All fields are required.",
        passwordLength: "Passwords must contain at least 8 characters.",
        passwordMismatch: "Password confirmation does not match.",
        unableToCreate: "Unable to create the account.",
      },
      verifyEmail: {
        metaTitle: "Verify Email",
        eyebrow: "Email Verification",
        title: "Verify your email before the first login",
        subtitle:
          "We sent a verification code to your inbox. Enter it here to activate sign-in and email-based two-factor authentication.",
        formTitle: "Verify account",
        email: "Email",
        code: "Verification code",
        submit: "Verify email",
        resend: "Resend code",
        backToLogin: "Back to login",
        nextTitle: "What happens next?",
        nextBody:
          "After verification, normal sign-in is enabled. Every login then requires a short-lived code sent to the same email address.",
        nextNote:
          "If you did not receive the message, check spam first and then request a fresh code.",
        invalidCode: "The verification code is invalid or expired.",
        required: "Email and verification code are required.",
        sent: "A verification code was sent to {{email}}.",
        resent:
          "If the account exists and is still pending verification, a new code was sent to {{email}}.",
      },
      twoFactor: {
        metaTitle: "Two-Factor Verification",
        eyebrow: "Two-Factor Authentication",
        title: "Confirm the login with the code sent to {{email}}",
        subtitle:
          "Your password was accepted. Complete the email verification step below to finish the login.",
        formTitle: "Enter verification code",
        code: "Verification code",
        submit: "Complete login",
        resend: "Resend code",
        startOver: "Start over",
        securityTitle: "Security note",
        securityBody:
          "The code expires quickly and is single-use. Starting the login again replaces the previous challenge automatically.",
        invalidCode: "The verification code is invalid or expired.",
        resent: "A fresh verification code was sent to {{email}}.",
      },
      forgotPassword: {
        metaTitle: "Forgot Password",
        eyebrow: "Password Reset",
        title: "Request a reset code by email",
        subtitle:
          "Enter the account email address and we will send a short-lived password reset code if the account exists.",
        formTitle: "Forgot password",
        email: "Email",
        submit: "Send reset code",
        backToLogin: "Back to login",
        afterTitle: "After the request",
        afterBody:
          "The email contains both the code and a direct link to the reset form. Existing sessions are not reused as proof of identity.",
        emailRequired: "Email is required.",
        sent: "If the account exists, a password reset message has been sent.",
      },
      resetPassword: {
        metaTitle: "Reset Password",
        eyebrow: "Reset Password",
        title: "Set a new password with your reset code",
        subtitle:
          "Use the email and reset code from the recovery message to choose a new password.",
        formTitle: "Choose a new password",
        email: "Email",
        code: "Reset code",
        password: "New password",
        confirmPassword: "Confirm new password",
        submit: "Update password",
        backToLogin: "Back to login",
        rulesTitle: "Reset rules",
        rulesBody:
          "Password reset codes expire quickly and become invalid after use. The new password must contain at least 8 characters.",
        invalidCode: "The reset code is invalid or expired.",
        allFieldsRequired: "All fields are required.",
        passwordLength: "Passwords must contain at least 8 characters.",
        passwordMismatch: "Password confirmation does not match.",
      },
      dashboard: {
        metaTitle: "Dashboard",
        eyebrow: "Dashboard",
        title: "Welcome back, {{name}}",
        subtitle:
          "Your current platform access is intentionally simple: you can review your account information and profile status from one place.",
        detailsTitle: "Account Details",
        fullName: "Full name",
        username: "Username",
        email: "Email",
        role: "Role",
        roleAdmin: "Administrator",
        roleUser: "User",
        status: "Status",
        active: "Active",
        inactive: "Inactive",
        emailVerification: "Email verification",
        verified: "Verified",
        pending: "Pending",
        joined: "Joined",
        updated: "Last updated",
        actionsTitle: "What you can do today",
        actionItems: {
          one: "Review your profile information and account status.",
          two:
            "Use email verification, password reset, and email two-factor authentication as part of your account lifecycle.",
          three: "Return to the public documentation and news sections using the main navigation.",
          four: "Prepare for future user-facing platform features as the site evolves.",
        },
      },
    },
    admin: {
      shared: {
        eyebrow: "xTaskjs Admin",
        manageUsers: "Manage Users",
        manageNews: "Manage News",
        logout: "Log out",
      },
      news: {
        metaTitle: "Manage News",
        title: "Manage News",
        subtitle: "Create, edit, publish, and remove content for the xTaskjs website.",
        create: "Create News",
        flash: {
          created: "News item created successfully.",
          updated: "News item updated successfully.",
          deleted: "News item deleted successfully.",
          default: "Action completed successfully.",
        },
        searchPlaceholder: "Search by title or summary...",
        searchAria: "Search news",
        search: "Search",
        clear: "Clear",
        resultCount: {
          "=0": "No items found",
          one: "{{count, number}} item found",
          other: "{{count, number}} items found",
        },
        resultsFor: "for \"{{search}}\"",
        created: "Created {{date}}",
        status: "Status: {{status}}",
        published: "Published",
        draft: "Draft",
        edit: "Edit",
        delete: "Delete",
        deleteConfirm: "Delete this news item?",
        emptyTitle: "No results",
        emptySearchPrefix: "No news items match your search.",
        emptySearchAction: "View all",
        emptyDefault: "Create your first post to publish updates in the public news section.",
        paginationAria: "News pagination",
        previous: "← Prev",
        next: "Next →",
        form: {
          createMetaTitle: "Create News",
          editMetaTitle: "Edit News",
          createTitle: "Create a News Item",
          editTitle: "Edit News Item",
          subtitle: "Write clear updates for developers following the xTaskjs ecosystem.",
          backToList: "Back to list",
          title: "Title",
          summary: "Summary",
          content: "Content",
          image: "Cover Image (JPEG, PNG, GIF, WebP - max 4 MB)",
          currentCover: "Current cover",
          removeImage: "Remove current image",
          publish: "Publish this news item",
          publishAction: "Publish News",
          saveAction: "Save Changes",
          allFieldsRequired: "All fields are required.",
        },
      },
      users: {
        metaTitle: "Manage Users",
        title: "Manage Users",
        subtitle: "Review registered accounts, assign administrator access, and control who can sign in.",
        flash: {
          roleUpdated: "User role updated successfully.",
          statusUpdated: "User status updated successfully.",
          default: "Action completed successfully.",
        },
        searchPlaceholder: "Search by name, username, or email...",
        searchAria: "Search users",
        search: "Search",
        clear: "Clear",
        resultCount: {
          "=0": "No users found",
          one: "{{count, number}} user found",
          other: "{{count, number}} users found",
        },
        resultsFor: "for \"{{search}}\"",
        status: "Status: {{status}}",
        active: "Active",
        inactive: "Inactive",
        joined: "Joined {{date}}",
        recentLoginsTitle: "Recent login locations",
        noLoginHistory: "No successful logins recorded yet.",
        registrationOrigin: "Registered from {{country}}",
        unknownLocation: "Unknown location",
        loginAt: "Login at {{date}}",
        ipAddress: "IP {{ip}}",
        viewDetails: "View details",
        promoteToAdmin: "Promote to Admin",
        convertToUser: "Convert to User",
        deactivate: "Deactivate",
        reactivate: "Reactivate",
        emptyTitle: "No users found",
        emptySearchPrefix: "No registered users match your search.",
        emptySearchAction: "View all users",
        emptyDefault: "Users will appear here as soon as registrations begin.",
        paginationAria: "Users pagination",
        previous: "← Prev",
        next: "Next →",
        roleAdmin: "Administrator",
        roleUser: "User",
        detail: {
          metaTitle: "User Details",
          title: "User details for {{name}}",
          subtitle: "Review account state, registration origin, and the full login-location history for this user.",
          backToUsers: "Back to users",
          accountTitle: "Account overview",
          historySummaryTitle: "History summary",
          historySummary: {
            "=0": "No successful login events recorded yet",
            one: "{{count, number}} successful login event recorded",
            other: "{{count, number}} successful login events recorded",
          },
          summaryItems: {
            one: "Registration country is stored on the user record for the first account creation request.",
            two: "Each successful two-factor login appends a timestamped location event with IP and user agent.",
            three: "Use this history to audit suspicious access patterns or confirm expected locations.",
          },
          loginHistoryTitle: "Full login history",
          loginHistorySubtitle: "Successful login events are ordered newest first.",
          registrationCountry: "Registration country",
          registrationIp: "Registration IP",
          country: "Country",
          region: "Region",
          city: "City",
          ipLabel: "IP address",
          userAgent: "User agent",
          paginationAria: "Login history pagination",
        },
      },
    },
  },
})
class EnglishSiteLocale {}

@InternationalizationLocale({
  locale: "es-ES",
  currency: "EUR",
  timeZone: "Europe/Madrid",
  translations: {
    site: {
      docs: {
        hub: {
          eyebrow: "Documentación",
          title: "Un solo lugar para la arquitectura, los paquetes, los decoradores, las integraciones y los ejemplos de xtaskjs.",
          subtitle:
            "Empieza por la visión general y después pasa a las páginas dedicadas a arquitectura del runtime, referencia de paquetes, referencia de decoradores y las aplicaciones de ejemplo oficiales publicadas en el monorepo xtask.",
          openArchitecture: "Abrir arquitectura",
          browseDecorators: "Ver decoradores",
          stats: "{{packages, number}} paquetes documentados + {{decorators, number}} decoradores + {{samples, number}} ejemplos de referencia",
          onThisPage: "En esta página",
          documentationSections: "Secciones de documentación",
          repo: "Repo:",
          scope: "Ámbito: paquetes del runtime, adaptadores, integraciones y ejemplos oficiales.",
          quickStartEyebrow: "Inicio rápido",
          quickStartTitle: "Arranca la aplicación xtask más pequeña útil",
          install: "Instalación",
          bootstrap: "Arranque",
          sectionsEyebrow: "Secciones",
          sectionsTitle: "Recorre la documentación por tema",
          documentationBadge: "Documentación",
          openSection: "Abrir {{label}}",
          highlightsEyebrow: "Puntos clave",
          highlightsTitle: "En qué se centra esta documentación",
          footer: "Sección de documentación integrada en xtaskjs.io y organizada alrededor de la estructura del monorepo original.",
        },
        architecture: {
          eyebrow: "Arquitectura",
          title: "Cómo arranca xtaskjs, resuelve rutas y extiende security dentro de un único runtime.",
          subtitle:
            "Esta página se centra en el ciclo de vida del framework: arranque de la aplicación, ejecución de peticiones y puntos de extensión de security superpuestos sobre la misma canalización de controladores.",
          quickStart: "Inicio rápido",
          openPackages: "Abrir paquetes",
          bootSequence: "Secuencia de arranque",
          bootSequenceText: "Descubrimiento del contenedor, selección del adaptador, inicio del ciclo de vida e inicialización de integraciones.",
          requestPath: "Ruta de petición",
          requestPathText: "Resolución de ruta, guards, pipes, middlewares, handlers y serialización final del adaptador.",
          securityLayering: "Capas de security",
          securityLayeringText: "Las estrategias, los servicios de autenticación, los decoradores y el enriquecimiento del contexto de ruta siguen siendo compatibles con DI.",
          documentation: "Documentación",
          focus: "Enfoque: ciclo de arranque, flujo de ejecución e integración de security.",
          bootstrapFlowEyebrow: "Flujo de arranque",
          bootstrapFlowTitle: "Cómo xtaskjs conecta el runtime",
          executionFlowEyebrow: "Flujo de ejecución",
          executionFlowTitle: "Canalización de peticiones y ciclo de vida de security",
          requestLifecycle: "Ciclo de vida de la petición HTTP",
          securityLifecycle: "Ciclo de vida de la extensión de security",
        },
        packages: {
          eyebrow: "Paquetes",
          title: "Referencia de los paquetes e integraciones del runtime de xtaskjs.",
          subtitle:
            "Esta página describe los paquetes principales del monorepo xtask, qué aporta cada uno, cómo encaja en el runtime y qué ejemplos oficiales lo demuestran en la práctica, incluido el nuevo módulo mailer.",
          browseCatalog: "Ver catálogo",
          openDecorators: "Abrir decoradores",
          openPackage: "Abrir página del paquete",
          backToCatalog: "Volver al catálogo",
          browseSamples: "Ver ejemplos",
          viewSource: "Ver código fuente",
          stats: "{{count, number}} paquetes documentados",
          coreRuntime: "Runtime principal",
          coreRuntimeText: "Bootstrap, contenedor DI, orquestación del ciclo de vida y arranque de la aplicación HTTP.",
          adapterLayer: "Capa de adaptadores",
          adapterLayerText: "Los adaptadores de Express y Fastify mantienen los mismos contratos de controlador y vista.",
          integrations: "Integraciones",
          integrationsText: "TypeORM, security y mailer añaden persistencia, autenticación y entrega de correo compatibles con el ciclo de vida.",
          documentation: "Documentación",
          focus: "Enfoque: responsabilidades de los paquetes, puntos de integración y ejemplos de código.",
          catalogEyebrow: "Catálogo",
          catalogTitle: "Paquetes del framework en el monorepo xtask",
          sampleCoverage: "Cobertura de ejemplos: {{sample}}",
          whatItProvides: "Qué ofrece",
          howItFits: "Cómo encaja",
          referenceSamples: "Ejemplos de referencia: {{sample}}",
          packagePath: "Ruta del paquete",
          installCommand: "Comando de instalación",
          atAGlanceEyebrow: "Resumen",
          atAGlanceTitle: "Qué controla este paquete en el runtime",
          runtimeChartEyebrow: "Mapa de uso",
          runtimeChartTitle: "Qué peso tiene este paquete dentro del runtime",
          flowEyebrow: "Flujo del paquete",
          flowTitle: "Cómo atraviesa este paquete las fases del runtime de xtaskjs",
          lifecycleEyebrow: "Ciclo de vida",
          lifecycleTitle: "Cómo actúa durante el arranque y el apagado",
          apiEyebrow: "Superficie API",
          apiTitle: "Exports representativos del paquete original",
          apiSource: "Origen: {{path}}",
          usageEyebrow: "Uso",
          usageTitle: "Flujo típico de adopción",
          exampleEyebrow: "Ejemplo",
          exampleTitle: "Fragmento de referencia",
          samplesEyebrow: "Ejemplos",
          samplesTitle: "Ejemplos oficiales para revisar después",
          relatedEyebrow: "Relacionados",
          relatedTitle: "Paquetes que suelen usarse junto a este",
          scoreLabel: "{{score}}/5",
          openRelatedPackage: "Abrir paquete",
          openSample: "Abrir ejemplo",
        },
        decorators: {
          eyebrow: "Decoradores",
          title: "Referencia de todos los decoradores públicos de xtaskjs para routing, ciclo de vida, DI, security, persistencia y correo.",
          subtitle:
            "Esta página enumera la superficie de decoradores del framework expuesta por los paquetes upstream, agrupada por caso de uso y etiquetada con el paquete del que procede cada decorador, además de pequeños ejemplos que puedes adaptar directamente.",
          browseCatalog: "Ver decoradores",
          openPackages: "Abrir paquetes",
          stats: "{{decorators, number}} decoradores en {{groups, number}} grupos",
          groupedByType: "Agrupados por tipo",
          groupedByTypeText: "Los decoradores de routing, ciclo de vida, DI, security, TypeORM y mailer se separan para mantener juntas las APIs similares.",
          packageAware: "Con conocimiento del paquete",
          packageAwareText: "Cada entrada muestra el paquete y la ruta original donde vive el decorador.",
          exampleDriven: "Guiado por ejemplos",
          exampleDrivenText: "Cada decorador incluye un pequeño fragmento tomado de los mismos patrones usados en los ejemplos de xtaskjs y en este sitio.",
          documentation: "Documentación",
          coverage: "Cobertura:",
          catalogEyebrow: "Catálogo",
          catalogTitle: "Grupos de decoradores por caso de uso",
          groupBadge: "Grupo de decoradores",
          countLabel: "decoradores",
        },
        samples: {
          eyebrow: "Ejemplos",
          title: "Aplicaciones de ejemplo oficiales para core, adaptadores, persistencia y security.",
          subtitle:
            "Usa las aplicaciones de ejemplo como la ruta más corta hacia el framework. Muestran las combinaciones principales del runtime publicadas en el monorepo original, incluido el ejemplo dedicado a mailer y los endpoints que expone cada una.",
          browseCatalog: "Ver ejemplos",
          openArchitecture: "Abrir arquitectura",
          stats: "{{count, number}} ejemplos de referencia documentados",
          startSmall: "Empieza pequeño",
          startSmallText: "Usa 01-new_app para entender el arranque mínimo con node-http y el flujo de registro de rutas.",
          swapAdapters: "Cambia adaptadores",
          swapAdaptersText: "Compara los ejemplos de Express y Fastify para ver cómo los controladores permanecen estables mientras cambia el servidor.",
          addIntegrations: "Añade integraciones",
          addIntegrationsText: "Pasa a los ejemplos de TypeORM, security y mailer cuando necesites persistencia, rutas protegidas o flujos de correo saliente.",
          documentation: "Documentación",
          focus: "Enfoque: ejemplos ejecutables, cobertura de endpoints y recorridos progresivos.",
          catalogEyebrow: "Catálogo",
          catalogTitle: "Aplicaciones de referencia incluidas en el monorepo",
          endpoints: "Endpoints",
          typicalFlow: "Flujo habitual",
        },
      },
      header: {
        announcement: "xTaskjs 1.0 ya está disponible: cuentas por rol, documentación y una interfaz personalizable.",
        why: "Por qué xTaskjs",
        learn: "Aprender",
        documentation: "Documentación",
        news: "Noticias",
        github: "Abrir xTaskjs en GitHub",
        login: "Iniciar sesión",
        register: "Registrarse",
        adminPanel: "Panel de administración",
        dashboard: "Panel personal",
        logout: "Cerrar sesión",
        menuOpen: "Abrir menú",
        menuClose: "Cerrar menú",
        themeToDark: "Cambiar a modo oscuro",
        themeToLight: "Cambiar a modo claro",
        languageLabel: "Idioma",
      },
      footer: {
        builtWith: "Creado con xTaskjs e inspirado en páginas modernas para plataformas de desarrollo.",
        github: "Acceder al proyecto en GitHub",
        adminAccess: "Acceso de administración",
      },
      home: {
        metaTitle: "xTaskjs",
        eyebrow: "Framework xTaskjs",
        title: "Construye flujos de trabajo Node.js resilientes con confianza.",
        tagline: "Orquestación moderna de flujos de trabajo con xTaskjs",
        stack:
          "Impulsado por decoradores, hooks de ciclo de vida y un núcleo de aplicación basado en clases",
        quickStart: "Inicio rápido",
        exploreGithub: "Explorar en GitHub",
        productionReady: "Stack listo para producción",
        productionItems: {
          one: "Módulos componibles con patrones de inyección de dependencias",
          two: "Soporte para el adaptador de Express con renderizado de plantillas",
          three: "Decoradores compartidos y herramientas comunes en un solo ecosistema",
        },
        learnTitle: "Aprende xTaskjs",
        guidesTitle: "Guías",
        guidesBody: "Empieza desde cero y publica tu primera aplicación xTaskjs rápidamente.",
        guidesAction: "Abrir inicio rápido",
        referenceTitle: "Referencia",
        referenceBody: "Entiende adaptadores, decoradores, renderizado de vistas y hooks del ciclo de vida.",
        referenceAction: "Ver paquetes",
        examplesTitle: "Ejemplos",
        examplesBody: "Usa ejemplos prácticos para APIs, jobs, colas y orquestación.",
        examplesAction: "Ver ejemplos",
        projectsTitle: "Proyectos xTaskjs",
        publishedOnNpm: "Publicado en npm: {{date}}",
        npmUnavailable: "datos de npm no disponibles",
        openDocumentationHub: "Abrir centro de documentación",
        communityTitle: "Comunidad",
        communityBody: "Sigue las novedades, contribuye módulos y comenta las prioridades del roadmap.",
        supportTitle: "Soporte",
        supportBody: "¿Necesitas ayuda en producción? Abre una incidencia o colabora con los maintainers.",
        latestNewsTitle: "Últimas noticias",
        latestNewsEmptyTitle: "Aún no hay noticias",
        latestNewsEmptyBody: "Las actualizaciones publicadas aparecerán aquí en cuanto el administrador las publique.",
        openFullNews: "Abrir la sección completa de noticias",
      },
      news: {
        metaTitle: "Noticias de xTaskjs",
        eyebrow: "Sala de noticias de xTaskjs",
        title: "Lanzamientos del framework, hitos del roadmap y novedades de la comunidad.",
        subtitle: "Todo lo que ocurre alrededor de xTaskjs en un solo lugar.",
        latestNewsTitle: "Últimas noticias",
        published: "Publicado {{date}}",
        emptyTitle: "Aún no hay noticias publicadas",
        emptyBody: "El equipo todavía no ha publicado novedades. Vuelve pronto.",
      },
    },
    auth: {
      admin: {
        metaTitle: "Acceso de administración",
        eyebrow: "Administración xTaskjs",
        title: "Acceso para gestionar noticias",
        subtitle: "Inicia sesión con una cuenta administradora para gestionar usuarios y publicaciones.",
        accessTitle: "Acceso de administrador",
        username: "Nombre de usuario",
        password: "Contraseña",
        submit: "Iniciar sesión",
        standardLogin: "Acceso estándar",
        backToNews: "Volver a noticias",
        expired: "Tu desafío de acceso ha caducado. Empieza de nuevo.",
      },
      login: {
        metaTitle: "Iniciar sesión",
        eyebrow: "Acceso a la cuenta",
        title: "Inicia sesión en tu cuenta xTaskjs",
        subtitle:
          "Los administradores gestionan el contenido y los usuarios de la plataforma. Los usuarios registrados acceden a su panel personalizado.",
        formTitle: "Iniciar sesión",
        identifier: "Nombre de usuario o correo",
        password: "Contraseña",
        submit: "Iniciar sesión",
        forgotPassword: "¿Has olvidado tu contraseña?",
        newHere: "¿Eres nuevo?",
        newHereBody:
          "Crea una cuenta de usuario para acceder a tu panel y preparar tu perfil para futuras funciones de la plataforma.",
        createAccount: "Crear una cuenta",
        newHereNote:
          "Los administradores también pueden usar el formulario estándar. Las operaciones exclusivas de administración siguen protegidas por comprobaciones de rol.",
        invalidCredentials: "Credenciales no válidas. Inténtalo de nuevo.",
        verified: "Correo verificado. Introduce tus credenciales para recibir un código de doble factor.",
        reset: "Contraseña actualizada. Introduce tus credenciales para recibir un código de doble factor.",
        expired:
          "Tu desafío de acceso ha caducado. Empieza de nuevo con tu usuario/correo y contraseña.",
      },
      register: {
        metaTitle: "Crear cuenta",
        eyebrow: "Registro",
        title: "Crea tu cuenta xTaskjs",
        subtitle:
          "El registro crea una cuenta de usuario estándar y después envía un código de verificación por correo antes de permitir la primera sesión autenticada.",
        formTitle: "Registrarse",
        fullName: "Nombre completo",
        username: "Nombre de usuario",
        email: "Correo electrónico",
        password: "Contraseña",
        confirmPassword: "Confirmar contraseña",
        submit: "Crear cuenta",
        alreadyRegistered: "¿Ya estás registrado?",
        alreadyRegisteredBody:
          "Usa la pantalla de acceso para entrar en tu panel o, si eres administrador, en el área de gestión.",
        goToLogin: "Ir al acceso",
        note:
          "Las contraseñas deben tener al menos 8 caracteres y las cuentas nuevas deben verificar su correo antes de iniciar sesión.",
        allFieldsRequired: "Todos los campos son obligatorios.",
        passwordLength: "Las contraseñas deben tener al menos 8 caracteres.",
        passwordMismatch: "La confirmación de la contraseña no coincide.",
        unableToCreate: "No se ha podido crear la cuenta.",
      },
      verifyEmail: {
        metaTitle: "Verificar correo",
        eyebrow: "Verificación de correo",
        title: "Verifica tu correo antes del primer acceso",
        subtitle:
          "Hemos enviado un código de verificación a tu bandeja de entrada. Escríbelo aquí para activar el acceso y la autenticación de doble factor por correo.",
        formTitle: "Verificar cuenta",
        email: "Correo electrónico",
        code: "Código de verificación",
        submit: "Verificar correo",
        resend: "Reenviar código",
        backToLogin: "Volver al acceso",
        nextTitle: "¿Qué ocurre después?",
        nextBody:
          "Después de la verificación se habilita el acceso normal. A partir de ahí, cada inicio de sesión requerirá un código de corta duración enviado al mismo correo.",
        nextNote:
          "Si no has recibido el mensaje, revisa primero el spam y después solicita un código nuevo.",
        invalidCode: "El código de verificación no es válido o ha caducado.",
        required: "El correo y el código de verificación son obligatorios.",
        sent: "Se ha enviado un código de verificación a {{email}}.",
        resent:
          "Si la cuenta existe y sigue pendiente de verificación, se ha enviado un código nuevo a {{email}}.",
      },
      twoFactor: {
        metaTitle: "Verificación en dos pasos",
        eyebrow: "Autenticación de doble factor",
        title: "Confirma el acceso con el código enviado a {{email}}",
        subtitle:
          "Tu contraseña fue aceptada. Completa la verificación por correo para finalizar el acceso.",
        formTitle: "Introduce el código de verificación",
        code: "Código de verificación",
        submit: "Completar acceso",
        resend: "Reenviar código",
        startOver: "Empezar de nuevo",
        securityTitle: "Nota de seguridad",
        securityBody:
          "El código caduca rápidamente y es de un solo uso. Si inicias el acceso de nuevo, se reemplaza automáticamente el desafío anterior.",
        invalidCode: "El código de verificación no es válido o ha caducado.",
        resent: "Se ha enviado un código nuevo a {{email}}.",
      },
      forgotPassword: {
        metaTitle: "He olvidado mi contraseña",
        eyebrow: "Restablecimiento de contraseña",
        title: "Solicita un código de restablecimiento por correo",
        subtitle:
          "Introduce el correo de la cuenta y enviaremos un código temporal de restablecimiento si la cuenta existe.",
        formTitle: "He olvidado mi contraseña",
        email: "Correo electrónico",
        submit: "Enviar código",
        backToLogin: "Volver al acceso",
        afterTitle: "Después de la solicitud",
        afterBody:
          "El correo incluye tanto el código como un enlace directo al formulario de restablecimiento. Las sesiones existentes no se reutilizan como prueba de identidad.",
        emailRequired: "El correo es obligatorio.",
        sent: "Si la cuenta existe, se ha enviado un mensaje de restablecimiento.",
      },
      resetPassword: {
        metaTitle: "Restablecer contraseña",
        eyebrow: "Restablecer contraseña",
        title: "Establece una nueva contraseña con tu código",
        subtitle:
          "Usa el correo y el código del mensaje de recuperación para elegir una nueva contraseña.",
        formTitle: "Elige una nueva contraseña",
        email: "Correo electrónico",
        code: "Código de restablecimiento",
        password: "Nueva contraseña",
        confirmPassword: "Confirmar nueva contraseña",
        submit: "Actualizar contraseña",
        backToLogin: "Volver al acceso",
        rulesTitle: "Reglas del restablecimiento",
        rulesBody:
          "Los códigos de restablecimiento caducan rápidamente y dejan de ser válidos tras su uso. La nueva contraseña debe tener al menos 8 caracteres.",
        invalidCode: "El código de restablecimiento no es válido o ha caducado.",
        allFieldsRequired: "Todos los campos son obligatorios.",
        passwordLength: "Las contraseñas deben tener al menos 8 caracteres.",
        passwordMismatch: "La confirmación de la contraseña no coincide.",
      },
      dashboard: {
        metaTitle: "Panel personal",
        eyebrow: "Panel personal",
        title: "Bienvenido de nuevo, {{name}}",
        subtitle:
          "Tu acceso actual a la plataforma es intencionadamente simple: puedes revisar la información de tu cuenta y el estado de tu perfil desde un solo lugar.",
        detailsTitle: "Detalles de la cuenta",
        fullName: "Nombre completo",
        username: "Nombre de usuario",
        email: "Correo electrónico",
        role: "Rol",
        roleAdmin: "Administrador",
        roleUser: "Usuario",
        status: "Estado",
        active: "Activo",
        inactive: "Inactivo",
        emailVerification: "Verificación del correo",
        verified: "Verificado",
        pending: "Pendiente",
        joined: "Alta",
        updated: "Última actualización",
        actionsTitle: "Qué puedes hacer hoy",
        actionItems: {
          one: "Revisar la información de tu perfil y el estado de tu cuenta.",
          two:
            "Usar la verificación por correo, el restablecimiento de contraseña y la autenticación de doble factor por correo como parte del ciclo de vida de tu cuenta.",
          three: "Volver a la documentación pública y a la sección de noticias mediante la navegación principal.",
          four: "Prepararte para futuras funcionalidades orientadas a usuarios a medida que evolucione el sitio.",
        },
      },
    },
    admin: {
      shared: {
        eyebrow: "Administración xTaskjs",
        manageUsers: "Gestionar usuarios",
        manageNews: "Gestionar noticias",
        logout: "Cerrar sesión",
      },
      news: {
        metaTitle: "Gestionar noticias",
        title: "Gestionar noticias",
        subtitle: "Crea, edita, publica y elimina contenido para el sitio web de xTaskjs.",
        create: "Crear noticia",
        flash: {
          created: "La noticia se ha creado correctamente.",
          updated: "La noticia se ha actualizado correctamente.",
          deleted: "La noticia se ha eliminado correctamente.",
          default: "La acción se ha completado correctamente.",
        },
        searchPlaceholder: "Buscar por título o resumen...",
        searchAria: "Buscar noticias",
        search: "Buscar",
        clear: "Limpiar",
        resultCount: {
          "=0": "No se han encontrado elementos",
          one: "{{count, number}} elemento encontrado",
          other: "{{count, number}} elementos encontrados",
        },
        resultsFor: "para \"{{search}}\"",
        created: "Creado {{date}}",
        status: "Estado: {{status}}",
        published: "Publicado",
        draft: "Borrador",
        edit: "Editar",
        delete: "Eliminar",
        deleteConfirm: "¿Eliminar esta noticia?",
        emptyTitle: "Sin resultados",
        emptySearchPrefix: "Ninguna noticia coincide con tu búsqueda.",
        emptySearchAction: "Ver todas",
        emptyDefault: "Crea tu primera publicación para mostrar novedades en la sección pública.",
        paginationAria: "Paginación de noticias",
        previous: "← Anterior",
        next: "Siguiente →",
        form: {
          createMetaTitle: "Crear noticia",
          editMetaTitle: "Editar noticia",
          createTitle: "Crear una noticia",
          editTitle: "Editar noticia",
          subtitle: "Escribe actualizaciones claras para desarrolladores que siguen el ecosistema xTaskjs.",
          backToList: "Volver al listado",
          title: "Título",
          summary: "Resumen",
          content: "Contenido",
          image: "Imagen de portada (JPEG, PNG, GIF, WebP - máximo 4 MB)",
          currentCover: "Portada actual",
          removeImage: "Eliminar imagen actual",
          publish: "Publicar esta noticia",
          publishAction: "Publicar noticia",
          saveAction: "Guardar cambios",
          allFieldsRequired: "Todos los campos son obligatorios.",
        },
      },
      users: {
        metaTitle: "Gestionar usuarios",
        title: "Gestionar usuarios",
        subtitle:
          "Revisa las cuentas registradas, asigna acceso de administrador y controla quién puede iniciar sesión.",
        flash: {
          roleUpdated: "El rol del usuario se ha actualizado correctamente.",
          statusUpdated: "El estado del usuario se ha actualizado correctamente.",
          default: "La acción se ha completado correctamente.",
        },
        searchPlaceholder: "Buscar por nombre, usuario o correo...",
        searchAria: "Buscar usuarios",
        search: "Buscar",
        clear: "Limpiar",
        resultCount: {
          "=0": "No se han encontrado usuarios",
          one: "{{count, number}} usuario encontrado",
          other: "{{count, number}} usuarios encontrados",
        },
        resultsFor: "para \"{{search}}\"",
        status: "Estado: {{status}}",
        active: "Activo",
        inactive: "Inactivo",
        joined: "Alta {{date}}",
        recentLoginsTitle: "Ubicaciones de inicio de sesión recientes",
        noLoginHistory: "Aún no hay inicios de sesión correctos registrados.",
        registrationOrigin: "Registro desde {{country}}",
        unknownLocation: "Ubicación desconocida",
        loginAt: "Inicio de sesión el {{date}}",
        ipAddress: "IP {{ip}}",
        viewDetails: "Ver detalle",
        promoteToAdmin: "Promocionar a administrador",
        convertToUser: "Convertir en usuario",
        deactivate: "Desactivar",
        reactivate: "Reactivar",
        emptyTitle: "No se han encontrado usuarios",
        emptySearchPrefix: "Ningún usuario registrado coincide con tu búsqueda.",
        emptySearchAction: "Ver todos los usuarios",
        emptyDefault: "Los usuarios aparecerán aquí en cuanto comiencen los registros.",
        paginationAria: "Paginación de usuarios",
        previous: "← Anterior",
        next: "Siguiente →",
        roleAdmin: "Administrador",
        roleUser: "Usuario",
        detail: {
          metaTitle: "Detalle de usuario",
          title: "Detalle del usuario {{name}}",
          subtitle: "Revisa el estado de la cuenta, el origen del registro y el historial completo de ubicaciones de inicio de sesión de este usuario.",
          backToUsers: "Volver a usuarios",
          accountTitle: "Resumen de la cuenta",
          historySummaryTitle: "Resumen del historial",
          historySummary: {
            "=0": "Todavía no hay inicios de sesión correctos registrados",
            one: "{{count, number}} inicio de sesión correcto registrado",
            other: "{{count, number}} inicios de sesión correctos registrados",
          },
          summaryItems: {
            one: "El país de registro se guarda en la ficha del usuario para la primera petición de creación de cuenta.",
            two: "Cada inicio de sesión correcto tras el segundo factor añade un evento con fecha, ubicación, IP y user agent.",
            three: "Usa este historial para auditar patrones de acceso sospechosos o confirmar ubicaciones esperadas.",
          },
          loginHistoryTitle: "Historial completo de accesos",
          loginHistorySubtitle: "Los inicios de sesión correctos se ordenan del más reciente al más antiguo.",
          registrationCountry: "País de registro",
          registrationIp: "IP de registro",
          country: "País",
          region: "Región",
          city: "Ciudad",
          ipLabel: "Dirección IP",
          userAgent: "User agent",
          paginationAria: "Paginación del historial de accesos",
        },
      },
    },
  },
})
class SpanishSiteLocale {}

void SiteInternationalizationConfiguration;
void SiteLocaleCookieResolver;
void EnglishSiteLocale;
void SpanishSiteLocale;